### PR TITLE
implement simple rolling update using depends_on

### LINKED ISSUE #190: Implement rolling update for instances.
### Describe the Feature

While updating the instance_type recently in preparation for a major version upgrade, both instances upgraded in parallel resulting in significant downtime.  I found a simple fix for this which I will submit as a pull request.

### Expected Behavior

At least one new node is in service at all times.

### Use Case

A Zero or minimal downtime deploy.

### Describe Ideal Solution

A rolling update.

### Alternatives Considered

I considered a blue/green update which I was even able to implement using the create_before_destroy. I can provide this implementation if anyone is interested.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by finchr**
## what

Implement a simple rolling update for the aws_rds_cluster_instance default instances.

## why

To implement a zero downtime deploy for simple changes.

## references

closes #190

### CODE REVIEW

**Comment by hans-d** [comment]
@finchr thanks. Did you also test this with a fresh deployment? (no reds deployed yet)

**Comment by hans-d** [comment]
@finchr I need to do some further review, but can you have a look at https://github.com/cloudposse/terraform-aws-rds-cluster/actions/runs/8057796243/job/22011400365?pr=191. At the end it shows what needs to be done.

**Comment by finchr** [comment]
> @finchr I need to do some further review, but can you have a look at https://github.com/cloudposse/terraform-aws-rds-cluster/actions/runs/8057796243/job/22011400365?pr=191. At the end it shows what needs to be done.

Hi @hans-d , it's done.

**Review by hans-d — APPROVED** [review]

**Pull request merged**
