### PR TITLE
add option for enabling global write forwarding

### PR DESCRIPTION
**Pull request by tdockseydt**
## what

Add option for enabling global write forwarding for aws rds cluster.
## why

- Ability to enable global write forwarding across our aws rds clusters. 
- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/aurora-global-database-write-forwarding-apg.html
- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#enable_global_write_forwarding

### CODE REVIEW

**Comment by hans-d** [comment]
@tdockseydt 
> README.md is outdated. Please run the following commands locally and push the file:
  make init
  make readme
Error: Process completed with exit code 1.

**Review by milldr — APPROVED** [review]

**Pull request merged**
