### PR TITLE
implement create_before_destroy on instances

### LINKED ISSUE #190: Implement rolling update for instances.
### Describe the Feature

While updating the instance_type recently in preparation for a major version upgrade, both instances upgraded in parallel resulting in significant downtime.  I found a simple fix for this which I will submit as a pull request.

### Expected Behavior

At least one new node is in service at all times.

### Use Case

A Zero or minimal downtime deploy.

### Describe Ideal Solution

A rolling update.

### Alternatives Considered

I considered a blue/green update which I was even able to implement using the create_before_destroy. I can provide this implementation if anyone is interested.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by finchr**
## what

I implemented create_before_destroy on the aws_rds_cluster_instance default instances.

## why

Making a change to any parameter that triggers a replace on a aws_rds_cluster_instance results in all instances being destroyed before attempting to create a new instance which causes an outage. This a faster (and safer) altenative to #191 

## references

This  closes #190 and is an alternative to #191

### CODE REVIEW

**Comment by frimik** [comment]
Is there an upgrade path for this? The `random_pet` name will require cluster destroy if upgrading the module.

**Comment by finchr** [comment]
> Is there an upgrade path for this? The `random_pet` name will require cluster destroy if upgrading the module.

Hi @frimik this will not destroy the cluster, it will only replace the db instances.

**Comment by hans-d** [comment]
@finchr hi, can you follow up on the reported check errors? thanks

**Comment by finchr** [comment]
> @finchr hi, can you follow up on the reported check errors? thanks

Hi @hans-d sorry for the delay, I fixed the issue pushed the change.

**Comment by hans-d** [comment]
@Gowiem can you have a look content wise?

**Comment by hans-d** [comment]
```
TestExamplesServerlessV2PostgresDisabled 2024-03-08T17:32:33Z logger.go:66: ╷
TestExamplesServerlessV2PostgresDisabled 2024-03-08T17:32:33Z logger.go:66: │ Error: Provider produced inconsistent result after apply
TestExamplesServerlessV2PostgresDisabled 2024-03-08T17:32:33Z logger.go:66: │ 
TestExamplesServerlessV2PostgresDisabled 2024-03-08T17:32:33Z logger.go:66: │ When applying changes to
TestExamplesServerlessV2PostgresDisabled 2024-03-08T17:32:33Z logger.go:66: │ module.rds_cluster_aurora_serverlessv2_postgres_13.random_pet.instance,
TestExamplesServerlessV2PostgresDisabled 2024-03-08T17:32:33Z logger.go:66: │ provider "provider[\"registry.terraform.io/hashicorp/random\"]" produced an
TestExamplesServerlessV2PostgresDisabled 2024-03-08T17:32:33Z logger.go:66: │ unexpected new value: .prefix: was cty.StringVal(""), but now null.
TestExamplesServerlessV2PostgresDisabled 2024-03-08T17:32:33Z logger.go:66: │ 
TestExamplesServerlessV2PostgresDisabled 2024-03-08T17:32:33Z logger.go:66: │ This is a bug in the provider, which should be reported in the provider's
TestExamplesServerlessV2PostgresDisabled 2024-03-08T17:32:33Z logger.go:66: │ own issue tracker.
```

**Comment by Gowiem** [comment]
@hans-d @finchr I'm going to call in @Nuru on this one... this is one of those types of changes we want to be very thoughtful about and I'm sure Jeremy will have opinions.

**Comment by finchr** [comment]
> This pull request now has conflicts. Could you fix it @finchr? 🙏

Conflicts resolved!

**Comment by finchr** [comment]
Hi @hans-d @Nuru , any update this?

**Comment by finchr** [comment]
Seriously? You sit on this months and then request that I fix merge conflicts and close on the same day?

**Comment by osterman** [comment]
Sorry about that. I think we have an edge condition with the mergify rules that caused that to happen. Please click the button to reopen the PR and work with someone in #pr-reviews channel to get this merged.

**Comment by finchr** [comment]
> Sorry about that. I think we have an edge condition with the mergify rules that caused that to happen. Please click the button to reopen the PR and work with someone in #pr-reviews channel to get this merged.

Hi @osterman I don't see a button or option to reopen the PR.

**Comment by osterman** [comment]
Hrm... looks like it won't work to reopen. 

image

**Comment by osterman** [comment]
We'll need a net-new PR.

**Comment by finchr** [comment]
OK, new PR is #213

**Pull request closed without merging**
