### PR TITLE
Additional inputs

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Add performance_insights_retention_period
* Add ca_cert_identifier
* Add preferred_maintenance_window to instances
* Add timeout to instances

## why
* Performance insights retention
* Add a ca cert identifier
* Put the maintenance window on cluster and instances
* Allow rds instances to be created without hitting a timeout

### CODE REVIEW

**Review by jamengual — APPROVED** [review]

**Review by jamengual — APPROVED** [review]

**Comment by alexjurkiewicz** [comment]
#125 is a fix for this

**Pull request merged**
