### PR TITLE
Allow to configure storage type for global databases

### PR DESCRIPTION
**Pull request by bentmann**
## what

Use existing `storage_type` variable for global DBs, too. Currently, it is only set for regional clusters.

## why

Aurora clusters offer two different storage types, standard and I/O-Optimized. Which one is employed for clusters in a global DB should be configurable to be able to realize cost savings that I/O-Optimized offers for certain workloads.

## references

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/rds_cluster#storage_type
- https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBCluster.html
- https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.Overview.StorageReliability.html#aurora-storage-type

### CODE REVIEW

**Comment by hans-d** [comment]
@bentmann I need to firther reviews this, but can you have a look at https://github.com/cloudposse/terraform-aws-rds-cluster/actions/runs/8024064623/job/22011254609?pr=189? at the end it shows what needs to be done.

**Comment by bentmann** [comment]
README was updated.

**Review by hans-d — APPROVED** [review]

**Comment by bentmann** [comment]
@hans-d Thanks for the merge and new release. I did note however that the Terraform registry still lists the [latest version of this module as 1.7.0](https://registry.terraform.io/modules/cloudposse/rds-cluster/aws/latest), missing the newer 1.7.1 and 1.8.0 releases/tags. Was the publishing step missed by chance?

**Comment by hans-d** [comment]
no clue re that. Need to check that out.

**Comment by hans-d** [comment]
Some automation seems to broken for some of the repos. Likely this is one of them. Currently checking what's needed to get it published.

**Pull request merged**
