### PR TITLE
added apply_immediately support to cluster_instance resource

### PR DESCRIPTION
**Pull request by RichardHeywood**
## what
* Add `apply_immediately` flag to the db instances 

## why
* Currently you can only apply changes immediately to the cluster resource. However the `aws_rds_cluster_instance` resource also supports the `apply_immediately` flag.
* Use case: Attempting to change the instance types for the RDS cluster causes the changes to be staged pending the next maintenance window. This change allows you to perform the updates before then.

### CODE REVIEW

**Comment by aknysh** [comment]
@RichardHeywood  thanks for the PR, LGTM
please run the following commands from the repo root

```
make init
make github/init
make readme
```

**Comment by Gowiem** [comment]
@RichardHeywood friendly ping on @aknysh's instructions above. We've attempted to rebuild the readme via our automation, but it doens't always take. If you can do those steps locally then we'll be good to get this shipped and obviously this is an important fix.

**Comment by nitrocode** [comment]
@RichardHeywood one more friendly ping :)

**Comment by RichardHeywood** [comment]
@nitrocode My apologies, this completely fell off my radar. Should be good to go now.

**Review by nitrocode — APPROVED** [review]

**Review by aknysh — APPROVED** [review]

**Pull request merged**
